export type RecordStatus = "Draft" | "Submitted" | "Returned" | "Approved" | "Invoiced";
export type ParticipantKyc = { serviceAgreement: boolean; consentForms: boolean; supportPlan: boolean; riskInformationReviewed: boolean; transportRequirementsConfirmed: boolean };
export type Participant = { id: string; name: string; preferred: string; ndis: string; dob?: string; phone: string; email: string; address: string; plan: string; planStart?: string; planEnd?: string; manager: string; nominee: string; emergency: string; alerts: string[]; goals: string[]; communication: string; mobility: string; transport: string; support: string; risks: string; allergies: string; preferences: string; kyc?: ParticipantKyc; status: "Active" | "Archived" };
export type Staff = { id: string; name: string; initials: string; position: string; status: "Active" | "On leave"; email: string; team: string };
export type Billable = { label: string; unit: string; quantity: number; rate: number; subtotal: number };
export type ServiceRecord = { id: string; clientId: string; date: string; start: string; end: string; staffId: string; type: string; location: string; support: string; response: string; outcome: string; observations: string; followUp: string; km: number; status: RecordStatus; created: string; updated: string; approvedBy?: string; correction?: string; billables: Billable[]; confirmed: boolean; invoiceId?: string; voiceId?: string };
export type Invoice = { id: string; clientId: string; recipient: string; issue: string; due: string; status: "Draft" | "Ready to send" | "Sent" | "Paid"; lines: Billable[]; subtotal: number; tax: number; total: number; recordIds: string[] };
export type Voice = { id: string; title: string; clientId: string; recordId?: string; duration: string; created: string; transcript: string; transcriptStatus: "Ready" | "Not transcribed" | "Unavailable"; generationStatus: "Not generated" | "Draft ready"; status: "Saved" | "Draft ready" | "Archived"; draft?: { support: string; response: string; outcome: string; observations: string; followUp: string } };
const date = (n = 0) => { const d = new Date(); d.setDate(d.getDate() + n); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; };
export const today = date();
export const participants: Participant[] = [
 {id:"p1",name:"Amelia Carter",preferred:"Mia",ndis:"431 208 775",phone:"0412 830 144",email:"amelia.carter@example.org",address:"14 Gilbert Street, Adelaide SA 5000",plan:"01 Feb 2026 – 31 Jan 2027",manager:"Bright Path Plan Management",nominee:"Sarah Carter (mother)",emergency:"Sarah Carter · 0411 200 619",alerts:["Anaphylaxis — carry EpiPen","Advance notice preferred for schedule changes"],goals:["Build independence with community access","Develop meal-planning skills","Increase confidence using public transport"],communication:"Allow extra processing time. Use clear, short instructions and check understanding.",mobility:"No mobility aid required.",transport:"Prefers familiar staff for community transport.",support:"Community access, daily living skills, meal planning.",risks:"May become anxious in crowded, unfamiliar settings.",allergies:"Peanuts — anaphylaxis",preferences:"Likes quiet cafés, gardening and written reminders.",status:"Active"},
 {id:"p2",name:"Noah Williams",preferred:"Noah",ndis:"431 662 090",phone:"0438 552 761",email:"noah.williams@example.org",address:"7 Jetty Road, Glenelg SA 5045",plan:"01 May 2026 – 30 Apr 2027",manager:"Horizon Plan Services",nominee:"Mark Williams (father)",emergency:"Mark Williams · 0403 151 884",alerts:["Uses a communication board when tired"],goals:["Practice independent travel","Build social connections"],communication:"Speak face-to-face; offer visual choices.",mobility:"No mobility aid required.",transport:"Wheelchair accessible vehicle not required.",support:"Social participation and travel training.",risks:"Check road-crossing safety.",allergies:"None recorded",preferences:"Enjoys basketball and music.",status:"Active"},
 {id:"p3",name:"Priya Nair",preferred:"Priya",ndis:"431 054 823",phone:"0401 788 025",email:"priya.nair@example.org",address:"29 Unley Road, Parkside SA 5063",plan:"15 Jan 2026 – 14 Jan 2027",manager:"Self-managed",nominee:"—",emergency:"Arun Nair · 0422 007 555",alerts:[],goals:["Maintain daily routines","Explore volunteering opportunities"],communication:"Prefers a written agenda before appointments.",mobility:"Uses a walking stick for longer distances.",transport:"Allow additional time for vehicle access.",support:"Daily living, appointments, community participation.",risks:"Uneven surfaces can affect balance.",allergies:"Latex sensitivity",preferences:"Enjoys art galleries and cooking.",status:"Active"},
 {id:"p4",name:"Ethan Brooks",preferred:"Ethan",ndis:"431 810 445",phone:"0420 293 014",email:"ethan.brooks@example.org",address:"3 / 18 Henley Beach Road, Mile End SA 5031",plan:"01 Mar 2026 – 28 Feb 2027",manager:"Bright Path Plan Management",nominee:"—",emergency:"Lara Brooks · 0419 007 221",alerts:["Medication reminder at 12:00"],goals:["Develop cooking confidence","Practice budgeting"],communication:"",mobility:"",transport:"",support:"Capacity building and meal preparation.",risks:"",allergies:"None recorded",preferences:"Likes step-by-step recipes.",status:"Active"},
 {id:"p5",name:"Grace Chen",preferred:"Grace",ndis:"431 425 992",phone:"0417 233 920",email:"grace.chen@example.org",address:"6 Stirling Street, Norwood SA 5067",plan:"01 Sep 2025 – 31 Aug 2026",manager:"New Horizons Plan Management",nominee:"Ming Chen (sister)",emergency:"Ming Chen · 0400 334 122",alerts:["Plan review due this month"],goals:["Build confidence in social settings","Maintain healthy routines"],communication:"Prefers one-to-one conversations.",mobility:"",transport:"",support:"Social and community participation.",risks:"",allergies:"Shellfish",preferences:"Enjoys swimming and podcasts.",status:"Active"}
];
export const staff: Staff[] = [
 {id:"s1",name:"Jordan Lee",initials:"JL",position:"Support Worker",status:"Active",email:"jordan.lee@noble.org.au",team:"Community Support"},
 {id:"s2",name:"Maya Thompson",initials:"MT",position:"Operations Lead",status:"Active",email:"maya.thompson@noble.org.au",team:"Operations"},
 {id:"s3",name:"Alex Rivera",initials:"AR",position:"Administrator",status:"Active",email:"alex.rivera@noble.org.au",team:"Administration"},
 {id:"s4",name:"Sam Patel",initials:"SP",position:"Support Worker",status:"On leave",email:"sam.patel@noble.org.au",team:"Community Support"}
];
export const serviceRates = [
 {id:"r1",name:"Community participation",unit:"Hour",rate:68.30,transport:true,transportUnit:"Kilometre",active:true,updated:"12 Sep 2026"},
 {id:"r2",name:"Daily living skills",unit:"Hour",rate:68.30,transport:true,transportUnit:"Kilometre",active:true,updated:"12 Sep 2026"},
 {id:"r3",name:"Support coordination",unit:"Hour",rate:100.14,transport:false,transportUnit:"—",active:true,updated:"02 Sep 2026"},
 {id:"r4",name:"Group community access",unit:"Hour",rate:34.15,transport:true,transportUnit:"Kilometre",active:true,updated:"18 Aug 2026"}
];
const stamp = (h:number,m:number) => { const d = new Date(); d.setHours(h,m,0,0); return d.toISOString(); };
export const initialRecords: ServiceRecord[] = [
 {id:"SR-1048",clientId:"p1",date:today,start:"09:00",end:"12:00",staffId:"s1",type:"Community participation",location:"Marion Shopping Centre",support:"Supported Mia with community access and grocery shopping. She selected items from her list with verbal prompting when needed.",response:"Mia appeared settled and engaged throughout. She asked for help comparing two products.",outcome:"Practised making independent choices in the community.",observations:"No incidents observed. A quieter environment supported focus.",followUp:"Bring the meal-planning worksheet next visit.",km:12.4,status:"Submitted",created:stamp(12,8),updated:stamp(12,8),billables:[{label:"Community participation",unit:"Hour",quantity:3,rate:68.3,subtotal:204.9},{label:"Provider travel",unit:"Kilometre",quantity:12.4,rate:1,subtotal:12.4}],confirmed:true},
 {id:"SR-1047",clientId:"p2",date:date(-1),start:"13:00",end:"15:30",staffId:"s1",type:"Community participation",location:"Glenelg foreshore",support:"Supported Noah to plan a route and practise crossing at marked crossings.",response:"Noah used his communication board to request a short break and rejoined after five minutes.",outcome:"Practised safe independent travel and communicating support preferences.",observations:"Warm afternoon. Water breaks offered.",followUp:"Repeat the foreshore route next week.",km:8,status:"Returned",created:stamp(15,45),updated:stamp(16,2),correction:"Please add the actual departure and return points for the recorded travel kilometres.",billables:[{label:"Community participation",unit:"Hour",quantity:2.5,rate:68.3,subtotal:170.75},{label:"Provider travel",unit:"Kilometre",quantity:8,rate:1,subtotal:8}],confirmed:true},
 {id:"SR-1046",clientId:"p3",date:date(-1),start:"09:30",end:"11:30",staffId:"s4",type:"Daily living skills",location:"Participant home",support:"Worked through a meal plan and prepared a vegetable stir-fry together.",response:"Priya followed the recipe and independently measured ingredients.",outcome:"Built confidence with meal preparation and sequencing.",observations:"Walking stick used for kitchen transitions.",followUp:"Check whether the written recipe was useful.",km:4.6,status:"Approved",created:stamp(11,30),updated:stamp(12,5),approvedBy:"Maya Thompson",billables:[{label:"Daily living skills",unit:"Hour",quantity:2,rate:68.3,subtotal:136.6},{label:"Provider travel",unit:"Kilometre",quantity:4.6,rate:1,subtotal:4.6}],confirmed:true},
 {id:"SR-1045",clientId:"p4",date:date(-2),start:"10:00",end:"12:00",staffId:"s1",type:"Daily living skills",location:"Participant home",support:"",response:"",outcome:"",observations:"",followUp:"",km:0,status:"Draft",created:stamp(10,15),updated:stamp(10,15),billables:[{label:"Daily living skills",unit:"Hour",quantity:2,rate:68.3,subtotal:136.6}],confirmed:false},
 {id:"SR-1044",clientId:"p5",date:date(-12),start:"14:00",end:"16:00",staffId:"s4",type:"Community participation",location:"Adelaide Botanic Garden",support:"Supported Grace to attend a guided garden walk and plan transport home.",response:"Grace spoke with two other attendees and requested information about the next group.",outcome:"Practised confidence in a group setting.",observations:"No concerns noted.",followUp:"Send group calendar to Grace.",km:6,status:"Invoiced",created:stamp(16,15),updated:stamp(16,30),approvedBy:"Maya Thompson",billables:[{label:"Community participation",unit:"Hour",quantity:2,rate:68.3,subtotal:136.6},{label:"Provider travel",unit:"Kilometre",quantity:6,rate:1,subtotal:6}],confirmed:true,invoiceId:"INV-2026-091"}
];
export const initialInvoices: Invoice[] = [{id:"INV-2026-091",clientId:"p5",recipient:"New Horizons Plan Management",issue:date(-10),due:date(4),status:"Sent",lines:[{label:"Community participation — 18 Sep",unit:"Hour",quantity:2,rate:68.3,subtotal:136.6},{label:"Provider travel — 18 Sep",unit:"Kilometre",quantity:6,rate:1,subtotal:6}],subtotal:142.6,tax:0,total:142.6,recordIds:["SR-1044"]}];
export const initialVoice: Voice[] = [
 {id:"VN-028",title:"Mia — community access follow-up",clientId:"p1",recordId:"SR-1048",duration:"01:42",created:"Today, 12:14 pm",transcript:"We went to Marion this morning. Mia brought her shopping list and chose most of the items by herself. I gave her a prompt when she was unsure about the labels. She seemed comfortable and asked to compare two options. Next time, bring the meal planning sheet.",transcriptStatus:"Ready",generationStatus:"Not generated",status:"Saved"},
 {id:"VN-027",title:"Noah travel practice",clientId:"p2",duration:"02:18",created:"Yesterday, 3:32 pm",transcript:"Noah planned the route to the foreshore with the map. We practised crossing at the lights. He requested a short break using his board, then continued.",transcriptStatus:"Ready",generationStatus:"Draft ready",status:"Draft ready",draft:{support:"Supported Noah to plan a route using a map and practise crossing at marked crossings.",response:"Noah requested a short break using his communication board, then rejoined the activity.",outcome:"Practised safe independent travel and communicating support preferences.",observations:"A break was offered during the outing.",followUp:"Repeat the foreshore route at the next visit."}},
 {id:"VN-026",title:"Priya meal preparation",clientId:"p3",duration:"00:56",created:"18 Sep, 11:48 am",transcript:"",transcriptStatus:"Unavailable",generationStatus:"Not generated",status:"Saved"}
];

export type ShiftRatio = "1:1" | "1:M" | "M:M";
export type RosterShift = { id: string; date: string; start: string; end: string; ratio: ShiftRatio; clientIds: string[]; staffIds: string[]; type: string; location: string; status: "Planned" | "Confirmed" | "Completed" };
export type BudgetCategory = { name: string; allocation: number };
export type ClientBudget = { clientId: string; planStart: string; planEnd: string; categories: BudgetCategory[] };

export const initialRosterShifts: RosterShift[] = [
  { id: "SH-2401", date: date(0), start: "09:00", end: "12:00", ratio: "1:1", clientIds: ["p1"], staffIds: ["s1"], type: "Community participation", location: "Marion Shopping Centre", status: "Confirmed" },
  { id: "SH-2402", date: date(0), start: "09:30", end: "12:30", ratio: "1:M", clientIds: ["p2", "p3"], staffIds: ["s2"], type: "Group community access", location: "Adelaide CBD", status: "Planned" },
  { id: "SH-2403", date: date(0), start: "13:00", end: "16:00", ratio: "M:M", clientIds: ["p4", "p5"], staffIds: ["s1", "s2"], type: "Group community access", location: "Botanic Gardens", status: "Confirmed" },
  { id: "SH-2404", date: date(1), start: "10:00", end: "12:00", ratio: "1:1", clientIds: ["p3"], staffIds: ["s1"], type: "Daily living skills", location: "Participant home", status: "Planned" },
  { id: "SH-2405", date: date(2), start: "09:00", end: "11:00", ratio: "1:1", clientIds: ["p5"], staffIds: ["s2"], type: "Community participation", location: "Local community", status: "Planned" }
];

export const initialClientBudgets: ClientBudget[] = [
  { clientId: "p1", planStart: "2026-02-01", planEnd: "2027-01-31", categories: [{ name: "Community participation", allocation: 10500 }, { name: "Daily living skills", allocation: 7000 }, { name: "Support coordination", allocation: 3000 }] },
  { clientId: "p2", planStart: "2026-05-01", planEnd: "2027-04-30", categories: [{ name: "Community participation", allocation: 8000 }, { name: "Daily living skills", allocation: 5000 }, { name: "Support coordination", allocation: 2000 }] },
  { clientId: "p3", planStart: "2026-01-15", planEnd: "2027-01-14", categories: [{ name: "Community participation", allocation: 7000 }, { name: "Daily living skills", allocation: 8500 }, { name: "Support coordination", allocation: 2500 }] },
  { clientId: "p4", planStart: "2026-03-01", planEnd: "2027-02-28", categories: [{ name: "Community participation", allocation: 4500 }, { name: "Daily living skills", allocation: 6500 }, { name: "Support coordination", allocation: 1500 }] },
  { clientId: "p5", planStart: "2025-09-01", planEnd: "2026-08-31", categories: [{ name: "Community participation", allocation: 11000 }, { name: "Daily living skills", allocation: 5000 }, { name: "Support coordination", allocation: 2500 }] }
];
