import { FormEvent, useState } from "react";
import { ArrowLeft, ArrowRight, BadgeCheck, CalendarDays, Check, CircleUserRound, FileText, HandHeart, LockKeyhole, Mail, ShieldCheck, Users, WalletCards } from "lucide-react";

type Screen = "landing" | "login" | "signup";

export default function PublicPages({ onEnterDemo }: { onEnterDemo: () => void }) {
  const [screen, setScreen] = useState<Screen>("landing");
  const [notice, setNotice] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");

  const navigate = (next: Screen) => { setScreen(next); setNotice(""); setMobileMenuOpen(false); };
  const submitLogin = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setNotice("Authentication is not connected in this prototype. No credentials were sent or saved. Use the Admin preview to explore the workspace.");
  };
  const submitSignup = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (password.length < 8) { setNotice("Choose a password with at least 8 characters."); return; }
    if (password !== confirmPassword) { setNotice("The passwords do not match."); return; }
    setNotice("Account creation is not connected yet. No account or credentials were created or saved.");
  };

  const Brand = () => <button type="button" className="flex items-center gap-2.5 text-left" onClick={() => navigate("landing")} aria-label="Noble Community Support home"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#1d4550] text-[#d4eee6]"><HandHeart size={21}/></span><span><b className="block text-[13px] font-bold tracking-[.12em] text-[#1f3945]">NOBLE</b><small className="block text-[9px] font-semibold tracking-[.16em] text-[#71858b]">COMMUNITY SUPPORT</small></span></button>;

  if (screen === "login" || screen === "signup") {
    const isSignup = screen === "signup";
    return <main className="public-site public-auth min-h-screen">
      <section className="public-auth-art" aria-label="Noble Community Support"><div className="public-auth-art-photo"/><div className="public-auth-art-shade"/><div className="public-auth-art-content"><Brand/><div className="mt-auto max-w-md pb-4"><div className="public-eyebrow text-white/75">ONE WORKSPACE · ONE ADMIN ROLE</div><h1 className="public-auth-heading serif">A thoughtful way to keep support in view.</h1><p className="mt-4 max-w-sm text-sm leading-6 text-white/80">Keep participant profiles, support notes, rosters and budgets together in one clear workspace.</p><button type="button" className="public-ghost-button mt-7" onClick={onEnterDemo}>Explore the admin preview <ArrowRight size={15}/></button></div><div className="text-[10px] text-white/60">Noble Community Support · Single-tenant workspace</div></div></section>
      <section className="public-auth-panel"><div className="public-auth-top"><Brand/><button type="button" className="public-back" onClick={() => navigate("landing")}><ArrowLeft size={14}/>Back to home</button></div>
        <div className="public-auth-form-wrap"><div className="public-eyebrow">{isSignup ? "FIRST ADMIN ACCOUNT" : "ADMIN ACCESS"}</div><h2 className="public-auth-title serif">{isSignup ? "Set up your workspace." : "Welcome back."}</h2><p className="mt-2 text-sm leading-6 text-[#718087]">{isSignup ? "Create the single administrator account for this Noble workspace." : "Sign in to your Noble Community Support workspace."}</p>
          <div className="public-prototype-note mt-5"><ShieldCheck size={16}/><span><b>Prototype sign-in</b><small>Authentication is not connected. This form does not create or verify accounts.</small></span></div>
          <form className="mt-6 space-y-4" onSubmit={isSignup ? submitSignup : submitLogin}>
            {isSignup && <label className="public-label">Full name<div className="public-input-wrap"><CircleUserRound size={15}/><input required autoComplete="name" placeholder="Your name"/></div></label>}
            <label className="public-label">Work email<div className="public-input-wrap"><Mail size={15}/><input type="email" required autoComplete="email" placeholder="name@organization.org.au"/></div></label>
            <label className="public-label">Password<div className="public-input-wrap"><LockKeyhole size={15}/><input type={showPassword ? "text" : "password"} required autoComplete={isSignup ? "new-password" : "current-password"} minLength={isSignup ? 8 : undefined} placeholder={isSignup ? "At least 8 characters" : "Enter your password"} value={password} onChange={event => setPassword(event.target.value)}/><button type="button" className="public-show-password" onClick={() => setShowPassword(value => !value)}>{showPassword ? "Hide" : "Show"}</button></div></label>
            {isSignup ? <label className="public-label">Confirm password<div className="public-input-wrap"><LockKeyhole size={15}/><input type={showPassword ? "text" : "password"} required autoComplete="new-password" placeholder="Enter password again" value={confirmPassword} onChange={event => setConfirmPassword(event.target.value)}/></div></label> : <div className="flex justify-end"><button type="button" className="public-inline-link" onClick={() => setNotice("Password reset is not connected. No reset email was sent.")}>Forgot password?</button></div>}
            {notice && <div className="public-form-notice" role="status">{notice}</div>}
            <button type="submit" className="public-primary-button w-full">{isSignup ? "Create Admin account" : "Sign in"}<ArrowRight size={15}/></button>
          </form>
          <div className="public-auth-switch">{isSignup ? "Already have an account?" : "Need to set up the workspace?"} <button type="button" className="public-inline-link" onClick={() => navigate(isSignup ? "login" : "signup")}>{isSignup ? "Sign in" : "Create the Admin account"}</button></div>
          <div className="public-divider"><span>OR</span></div>
          <button type="button" className="public-secondary-button w-full" onClick={onEnterDemo}>Open the Admin preview</button>
          <p className="mt-6 text-center text-[10px] leading-4 text-[#8b979a]">Single-tenant prototype · no organization selector · all workspace features are shown in the Admin preview.</p>
        </div>
      </section>
    </main>;
  }

  return <main className="public-site min-h-screen">
    <header className="public-header"><Brand/><nav className={`public-nav-links ${mobileMenuOpen ? "is-open" : ""}`} aria-label="Main navigation"><a href="#approach" onClick={() => setMobileMenuOpen(false)}>Our approach</a><a href="#workspace" onClick={() => setMobileMenuOpen(false)}>The workspace</a><a href="#contact" onClick={() => setMobileMenuOpen(false)}>Contact</a></nav><div className="flex items-center gap-2"><button type="button" className="public-text-button hidden sm:inline-flex" onClick={() => navigate("login")}>Admin sign in</button><button type="button" className="public-header-cta" onClick={() => navigate("signup")}>Create Admin account <ArrowRight size={14}/></button><button type="button" className="public-menu-button" aria-label="Toggle navigation" aria-expanded={mobileMenuOpen} onClick={() => setMobileMenuOpen(value => !value)}><span/><span/></button></div></header>
    <section className="public-hero"><div className="public-hero-copy"><div className="public-eyebrow"><span className="public-eyebrow-dot"/>PERSON-LED SUPPORT, CLEARLY CONNECTED</div><h1 className="public-display serif">Support that makes room for <em>more life.</em></h1><p className="public-hero-lede">A considered home for the people, plans and everyday details behind great community support.</p><div className="mt-7 flex flex-wrap gap-3"><button type="button" className="public-primary-button" onClick={onEnterDemo}>Explore the Admin workspace <ArrowRight size={15}/></button><button type="button" className="public-secondary-button" onClick={() => navigate("login")}>Admin sign in</button></div><div className="public-hero-proof"><span><Check size={14}/>One tenant workspace</span><span><Check size={14}/>One administrator role</span></div></div><div className="public-hero-visual"><img src="/manus-storage/noble-landing-hero_eb3d80e2.webp" alt="Two adults sharing a relaxed community walk in a green park"/><div className="public-image-caption"><span className="public-caption-icon"><HandHeart size={15}/></span><span><b>Built around the person</b><small>Support that follows their goals, choices and pace.</small></span></div><div className="public-image-stamp"><span className="public-stamp-dot"/>Care, connected</div></div></section>
    <section id="approach" className="public-value-strip"><div><span className="public-value-number">01</span><span><b>Know the person</b><small>Profiles, plans, consent and goals together.</small></span></div><div><span className="public-value-number">02</span><span><b>See the support</b><small>Progress notes, incidents and travel records in context.</small></span></div><div><span className="public-value-number">03</span><span><b>Plan with clarity</b><small>Flexible rosters and participant budgets at a glance.</small></span></div></section>
    <section id="workspace" className="public-workspace-section"><div className="public-section-heading"><div className="public-eyebrow">A CLEARER DAILY VIEW</div><h2 className="serif">The details belong<br/>in one place.</h2><p>From the first conversation to the next support shift, keep the important context close at hand.</p></div><div className="public-feature-grid"><article className="public-feature-card public-feature-card-main"><div className="public-feature-icon"><Users size={18}/></div><div className="public-feature-kicker">PARTICIPANT FILES</div><h3 className="serif">A folder for the whole story.</h3><p>Participant profiles, service agreements, goals, progress notes, incidents, kilometres and correspondence—organized in a familiar, year-and-month structure.</p><div className="public-folder-list"><span><FileText size={13}/>Support plans & goals</span><span><CalendarDays size={13}/>Progress notes by month</span><span><BadgeCheck size={13}/>Consent & agreements</span></div></article><article className="public-feature-card"><div className="public-feature-icon public-feature-icon-blue"><CalendarDays size={18}/></div><div className="public-feature-kicker">FLEXIBLE ROSTERING</div><h3 className="serif">The right people, in rhythm.</h3><p>Plan one-to-one and shared supports with a clear view of staff, participants and time.</p></article><article className="public-feature-card"><div className="public-feature-icon public-feature-icon-sand"><WalletCards size={18}/></div><div className="public-feature-kicker">BUDGET VISIBILITY</div><h3 className="serif">Understand what is planned.</h3><p>See plan allocations alongside approved support, items under review and future commitments.</p></article></div></section>
    <section className="public-admin-band"><div className="public-admin-mark"><LockKeyhole size={18}/></div><div><div className="public-eyebrow text-white/70">SIMPLE ACCESS MODEL</div><h2 className="serif">One tenant. One Admin role.</h2><p>A single administrator account has access to the complete workspace—no separate staff, reviewer or manager roles to navigate.</p></div><button type="button" className="public-ghost-button" onClick={() => navigate("signup")}>Create the Admin account <ArrowRight size={15}/></button></section>
    <footer id="contact" className="public-footer"><div className="flex flex-wrap items-center justify-between gap-5"><div><Brand/><p className="mt-3 max-w-sm text-[11px] leading-5 text-[#7b898e]">A single workspace for connected community support. This prototype uses sample data and is not a production record system.</p></div><div className="flex flex-wrap items-center gap-5"><button type="button" className="public-footer-link" onClick={() => navigate("login")}>Admin sign in</button><button type="button" className="public-footer-link" onClick={() => navigate("signup")}>Create account</button><button type="button" className="public-footer-link" onClick={onEnterDemo}>Open preview</button></div></div><div className="public-footer-bottom"><span>© 2026 Noble Community Support</span><span>Prototype · secure storage and authentication not connected</span></div></footer>
  </main>;
}
